// This file is auto-generated by @hey-api/openapi-ts

export type Body_items_update_item = {
    file?: ((Blob | File) | null);
    title?: (string | null);
    description?: (string | null);
    alt_text?: (string | null);
    veneration?: (string | null);
    commission_date?: (string | null);
    owned_since?: (string | null);
    monitory_value?: (number | null);
    collection_id?: (number | null);
};

export type Body_items_upload_image = {
    file: (Blob | File);
    title: string;
    description?: (string | null);
    alt_text?: (string | null);
    veneration?: (string | null);
    commission_date?: (string | null);
    owned_since?: (string | null);
    monitory_value?: (number | null);
    collection_id: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CollectionCreate = {
    name: string;
    description?: (string | null);
    is_public?: boolean;
};

export type CollectionPublic = {
    name: string;
    description?: (string | null);
    is_public?: boolean;
    id: number;
    created_by: number;
    created_date: string;
};

export type CollectionsPublic = {
    data: Array<CollectionPublic>;
    count: number;
};

export type CollectionUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_public?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemPublic = {
    title: string;
    veneration?: (string | null);
    description?: (string | null);
    commission_date?: (string | null);
    owned_since?: (string | null);
    monitory_value?: (number | null);
    filename: string;
    file_path: string;
    file_size: number;
    mime_type: string;
    width?: (number | null);
    height?: (number | null);
    alt_text?: (string | null);
    id: number;
    owner_id: number;
    collection_id: number;
    upload_date: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    veneration?: (string | null);
    commission_date?: (string | null);
    owned_since?: (string | null);
    monitory_value?: (number | null);
    description?: (string | null);
    alt_text?: (string | null);
    collection_id?: (number | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CollectionsReadCollectionsData = {
    limit?: number;
    skip?: number;
};

export type CollectionsReadCollectionsResponse = (CollectionsPublic);

export type CollectionsCreateCollectionData = {
    requestBody: CollectionCreate;
};

export type CollectionsCreateCollectionResponse = (CollectionPublic);

export type CollectionsReadCollectionData = {
    id: number;
};

export type CollectionsReadCollectionResponse = (CollectionPublic);

export type CollectionsUpdateCollectionData = {
    id: number;
    requestBody: CollectionUpdate;
};

export type CollectionsUpdateCollectionResponse = (CollectionPublic);

export type CollectionsDeleteCollectionData = {
    id: number;
};

export type CollectionsDeleteCollectionResponse = (Message);

export type ItemsReadItemsData = {
    collectionId?: (number | null);
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsReadItemData = {
    id: number;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    formData?: Body_items_update_item;
    id: number;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsUpdateItemMetadataData = {
    id: number;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemMetadataResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: number;
};

export type ItemsDeleteItemResponse = (Message);

export type ItemsUploadImageData = {
    formData: Body_items_upload_image;
};

export type ItemsUploadImageResponse = (ItemPublic);

export type ItemsGetImageFileData = {
    id: number;
};

export type ItemsGetImageFileResponse = (unknown);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: number;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: number;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: number;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);